#!/usr/bin/python3
import models
from uuid import uuid4
from datetime import datetime


class BaseModel:

    def to_dict(self):
        # Create a dictionary copy of the instance's attributes

        rdict = self.__dict__.copy()
        rdict["created_at"] = self.created_at.isoformat()
        rdict["updated_at"] = self.updated_at.isoformat()
        rdict["__class__"] = self.__class__.__name__
        return rdict

    def __init__(self, *args, **kwargs):
        # Define the time format for date parsing


        timeform = "%Y-%m-%dT%H:%M:%S.%f"
        # Generate a unique ID using uuid4()
        self.id = str(uuid4())
        self.created_at = datetime.today()
        self.updated_at = datetime.today()
        # If keyword arguments are provided during initialization
        if len(kwargs) != 0:
            for k, v in kwargs.items():
                if k == "created_at" or k == "updated_at":
                    self.__dict__[k] = datetime.strptime(v, timeform)
                else:
                    self.__dict__[k] = v
        else:
            models.storage.new(self)

    def save(self):
        # Update the update timestamp to the current datetime

        self.updated_at = datetime.today()
        models.storage.save()



    def __str__(self):
        # Get the class name.
        clname = self.__class__.__name__
        return "[{}] ({}) {}".format(clname, self.id, self.__dict__)
